{
 "title": "NATS Servers",
 "description": "NATS Server Dashboard",
 "tags": [ "nats" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NATS pods",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "nats_varz_version" }
   ]
  },
  { "title": "OS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Server CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "nats_varz_cpu", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Server Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "nats_varz_mem", "legendFormat": "{{pod}}" }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Bytes per second  In",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "rate(nats_varz_in_bytes[5m])", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "NATS Msgs per second In",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(nats_varz_in_msgs[5m])", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Bytes per second Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "rate(nats_varz_out_bytes[5m])", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "NATS Msgs per second Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(nats_varz_out_msgs[5m])", "legendFormat": "{{pod}}" }
   ]
  },
  { "title": "Client Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nats_varz_connections", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nats_varz_subscriptions", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Slow Consumers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nats_varz_slow_consumers", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}